# Generated by Django 5.1.1 on 2024-09-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='passengers_waiting',
        ),
        migrations.AddField(
            model_name='busstop',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='busstop',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
